all:
  children:
    ldap:
      hosts:
        ldap-server:
          ansible_host: "{{ lookup('env', 'LDAP_SERVER_IP') }}"
          ansible_user: reviewer
          ansible_ssh_private_key_file: ~/.ssh/reviewer
    app:
      hosts:
        app-server:
          ansible_host: "{{ lookup('env', 'APP_SERVER_IP') }}"
          ansible_user: reviewer
          ansible_ssh_private_key_file: ~/.ssh/reviewer 